### ISSUE TITLE
Chat event not firing

### ISSUE THREAD

**Issue by sigmasoldi3r** [garrettjoecox/scriptserver-event#6]
Using the following code:

```js
const config = require('./server.config');
const Server = require('scriptserver');

const app = new Server({
  core: {
    jar: config.jar,
    args: [
      ...config.args
    ]
  }
});

app.use(require('scriptserver-event'));

app.on('chat', evt => {
  console.log('Chat event: ', evt);
  app.send('say Test chat event')
});

app.start();
```

Yields nothing on console or in-game chat:

```
[11:29:20] [Server thread/INFO] [minecraft/DedicatedServer]: <player> test events
```

Maybe it's related to https://github.com/garrettjoecox/scriptserver-command/issues/3

Node v10.7.0
NPM 6.4.1
scriptserver latest
scriptserver-event latest

**Comment by garrettjoecox** [comment]
Again unable to reproduce, if you still experience this on the newest version submit another issue

**Comment by LoggeL** [comment]
Same problem here running spigot-1.16.1

The stdout shows the following: 
`[12:15:49] [Async Chat Thread - #0/INFO]: <LoggeL> test`

The fixed regex would look like this:
`^\[[\d:]{8}\] \[Async Chat Thread - #0\/INFO]: <(\w+)> (.*)`

Not sure if it's the same for vanilla aswell.
